### ISSUE TITLE
Support for GigE camera

### ISSUE THREAD

**Issue by jmarsik** [fhwedel-hoe/pylon_usb-instant-camera#1]
Continuing with the discussion from main Basler driver repo (see https://github.com/basler/pylon-ros-camera/issues/58#issuecomment-879867714) ...

I have tried your `ros2_gige` branch, it compiles successfully, but I'm unable to run it.

```bash
ros2 run pylon_usb_instant_camera node
```

Output:
```
Warning: Cannot change group of /dev/shm/sem.siso_fglib_init_lock to 'video'.
Warning: Cannot change group of /dev/shm/sem.siso_fglib_mssync_GenTLSession_lock to 'video'.
Warning: Cannot change group of /dev/shm/sem.siso-hw-me6-init to 'video'.
Warning: Cannot change group of /dev/shm/sem.siso_mE_0_Bar_0_Page_4 to 'video'.
Warning: Cannot change group of /dev/shm/sem.siso_mE_1_Bar_0_Page_4 to 'video'.
Warning: Cannot change group of /dev/shm/sem.siso_mE_2_Bar_0_Page_4 to 'video'.
Warning: Cannot change group of /dev/shm/sem.siso_mE_3_Bar_0_Page_4 to 'video'.
Warning: Cannot change group of /dev/shm/sem.siso_mE_4_Bar_0_Page_4 to 'video'.
Warning: Cannot change group of /dev/shm/sem.siso_mE_5_Bar_0_Page_4 to 'video'.
Warning: Cannot change group of /dev/shm/sem.siso_mE_6_Bar_0_Page_4 to 'video'.
Warning: Cannot change group of /dev/shm/sem.siso_mE_7_Bar_0_Page_4 to 'video'.
Warning: Cannot change group of /dev/shm/sem.siso_mE_8_Bar_0_Page_4 to 'video'.
Warning: Cannot change group of /dev/shm/sem.siso_mE_9_Bar_0_Page_4 to 'video'.
Warning: Cannot change group of /dev/shm/sem.siso_mE_10_Bar_0_Page_4 to 'video'.
Warning: Cannot change group of /dev/shm/sem.siso_mE_11_Bar_0_Page_4 to 'video'.
Warning: Cannot change group of /dev/shm/sem.siso_mE_12_Bar_0_Page_4 to 'video'.
Warning: Cannot change group of /dev/shm/sem.siso_mE_13_Bar_0_Page_4 to 'video'.
Warning: Cannot change group of /dev/shm/sem.siso_mE_14_Bar_0_Page_4 to 'video'.
Warning: Cannot change group of /dev/shm/sem.siso_mE_15_Bar_0_Page_4 to 'video'.
Warning: Cannot change group of /dev/shm/sem.siso_mE_16_Bar_0_Page_4 to 'video'.
Warning: Cannot change group of /dev/shm/sem.siso_mE_17_Bar_0_Page_4 to 'video'.
Warning: Cannot change group of /dev/shm/sem.siso_mE_18_Bar_0_Page_4 to 'video'.
Warning: Cannot change group of /dev/shm/sem.siso_mE_19_Bar_0_Page_4 to 'video'.
Warning: Cannot change group of /dev/shm/sem.siso_mE_20_Bar_0_Page_4 to 'video'.
Warning: Cannot change group of /dev/shm/sem.siso_mE_21_Bar_0_Page_4 to 'video'.
Warning: Cannot change group of /dev/shm/sem.siso_mE_22_Bar_0_Page_4 to 'video'.
Warning: Cannot change group of /dev/shm/sem.siso_mE_23_Bar_0_Page_4 to 'video'.
Warning: Cannot change group of /dev/shm/sem.siso_mE_24_Bar_0_Page_4 to 'video'.
Warning: Cannot change group of /dev/shm/sem.siso_mE_25_Bar_0_Page_4 to 'video'.
Warning: Cannot change group of /dev/shm/sem.siso_mE_26_Bar_0_Page_4 to 'video'.
Warning: Cannot change group of /dev/shm/sem.siso_mE_27_Bar_0_Page_4 to 'video'.
Warning: Cannot change group of /dev/shm/sem.siso_mE_28_Bar_0_Page_4 to 'video'.
Warning: Cannot change group of /dev/shm/sem.siso_mE_29_Bar_0_Page_4 to 'video'.
Warning: Cannot change group of /dev/shm/sem.siso_mE_30_Bar_0_Page_4 to 'video'.
Warning: Cannot change group of /dev/shm/sem.siso_mE_31_Bar_0_Page_4 to 'video'.
terminate called after throwing an instance of 'GenICam_3_1_Basler_pylon::AccessException'
```

Unfortunately I do not know how to proceed, I do not have enough experience with C++ to debug this :(

**Comment by fhwedel-hoe** [comment]
I did not expect success. I am pretty much shooting in the dark here. :D I changed the code so more debug information should be printed. Please try again.

**Comment by jmarsik** [comment]
The output is now like this:

```
jmarsik@jmg14:~/robocon_ros2_ws$ ros2 run pylon_usb_instant_camera node 
Failed to write enumeration value. Enum entry is not writable : AccessException thrown in node 'PixelFormat' while calling 'PixelFormat.SetIntValue()' (file 'Enumeration.cpp', line 151)
terminate called after throwing an instance of 'GenICam_3_1_Basler_pylon::AccessException'
```

My camera is Basler acA2440-20gc and is set to Bayer RG 8 color format in Pylon viewer.

**Comment by hoehermann** [comment]
Hm. Okay. Apparently, Basler's Ethernet cameras include some kind of access control not present in the USB variants. Feel free to remove or comment out the line

https://github.com/fhwedel-hoe/pylon_usb-instant-camera/blob/27eb12b84555e4782ee2d5a5aca8267f39e8763b/src/main.cpp#L57

and try again. For now, the driver expects the pixel format RGB8Packed. Please manually set the pixel format beforehand (by using the Pylon Viewer).

**Comment by jmarsik** [comment]
It's not access control actually. I have realized that our camera (acA2440-20gc) does not support RGB8 encoding (see https://docs.baslerweb.com/pixel-format). Therefore I changed it in the code to Bayer RGGB 8 and it started working!

I have made some other changes - timeout while grabbing should not result in node termination IMHO, so I catched the exception and logged a warning. I have added debug log message for each grabbed frame with width, height, size in bytes and stride. I have also used stride for ROS2 image step field.

Should I do a pull request into your ros2_gige branch or can you reproduce those changes just from my description? Do you have time to somehow modify this code to allow for USB or GigE camera and to allow either pixel format (Pylon and ROS) set by parameters or to allow pixel format to be specified just in camera configuration and the node will adapt itself (when possible)?

It would be also nide to be able to specify which GigE camera (by device ID) you would like to connect to. We have only one so it's not a problem for us, but it can be useful to others.

Thank you.

**Comment by jmarsik** [comment]
See here https://github.com/jmarsik/pylon_usb-instant-camera/commit/a6ee6a38646bca2b59e58ccce5326dc0c0ed4f2b :)

**Comment by hoehermann** [comment]
Nice work!

> Should I do a pull request

No need. I can pull your changes into my branch next month. I am on vacation right now.

> allow for USB or GigE camera

As far as I can tell, USB/GigE needs to be decided on compile-time. I can probably adapt the CMakeLists to produce both, a USB and a GigE node.

> allow either pixel format

I am opting for "load all settings via pfs file and ROS follows camera setting".

> We have only one

Same here. I like to keep the scope of this project to minimal "works for me". Others may chime in for adaptions – just like you did. :) Apart from that, I expect the official driver to have ROS2 support some day. For this reason, I do not see the need to expand this project in every direction.

**Comment by jmarsik** [comment]
Check this commit https://github.com/jmarsik/pylon_usb-instant-camera/commit/649faacbb2d351bdde633c9284ffa07ed6199fb1

I have changed it to use CBaslerUniversalInstant camera to support (I hope) both USB and GigE cameras. And I have added simple parameters to identify camera you want in case of multiple accessible cameras.

The repo and the package should be then renamed to pylon-instant-camera :)

PFS file - you mean that one should configure the camera by using a PFS file in Pylon Viewer to configure the camera, then connect with the instant driver package with minimal parameters, right?

**Comment by jmarsik** [comment]
Two more commits in my branch https://github.com/jmarsik/pylon-instant-camera/tree/ros2_gige_jm ... renamed of the node and package (without usb), bumped package version and corrected license tag in package.xml.

**Comment by hoehermann** [comment]
That is great news! Good work. :slightly_smiling_face: 

Regarding PFS: In line https://github.com/fhwedel-hoe/pylon_usb-instant-camera/blob/ros2/src/main.cpp#L106 I added a parameter for the binning (which was the only parameter I was playing around with). Although useful in production, I quickly realized it was impractical to map all parameters in code. Using a ROS2 parameter to supply a path to a PFS file, then loading it via `Pylon::CFeaturePersistence` should cover all bases with minimal development effort.

**Comment by fhwedel-hoe** [comment]
I tested the updated version, made some adjustments and added the option of loading a feature file as created by the pylon Viewer. @jmarsik, does https://github.com/fhwedel-hoe/pylon_usb-instant-camera/tree/ros2_gige work for you, too? Then we would have found a common ground for USB and GigE in one driver. :)

**Comment by jmarsik** [comment]
Hello Hermann, sorry to keep you waiting. I have finally tried your changes and basics seem to be working. I will try more in the coming days. One thing was a problem - our camera does not provide ResultingFrameRate, accessing it results in an access violation. I have made a change that probably solves it, please check #2 ... thank you.

Are you thinking about renaming the repository, so that it matches the package name? Of course that would mean that existing hyperlinks stop working and that could be a problem ...

Are you open to PRs regarding coding style or comment uniformity, README updates etc?
What about the ROS1 version, should we also update it so that it supports both USB and GigE cameras? Or maybe you could drop it entirely, because other drivers for Basler cameras for ROS1 exist?

**Comment by jmarsik** [comment]
Oh, now I see! You have already created a new repo with an updated name, perfect. This is obviously the best solution, having both repos with a deprecation notice.

I will submit the PR regarding ResultingFrameRate to the new repo as well.

**Comment by jmarsik** [comment]
PR here https://github.com/fhwedel-hoe/pylon_instant_camera/pull/1

My other question still applies: Are you open to PRs regarding coding style or comment uniformity, README updates etc?

**Comment by jmarsik** [comment]
I have made a little promotion here: https://github.com/basler/pylon-ros-camera/issues/58#issuecomment-953018911

**Comment by fhwedel-hoe** [comment]
Hi @jmarsik nice to hear from you.

> Are you open to PRs regarding coding style or comment uniformity, README updates etc?

Yes.

> What about the ROS1 version, should we also update it so that it supports both USB and GigE cameras? Or maybe you could drop it entirely, because other drivers for Basler cameras for ROS1 exist?

The ROS2 branch has become quite different from the ROS1 branch. As of today, ROS2 seems to be working fine for me. Since I have no intention to switch back to ROS1, I have no incentive to maintain the ROS1 branch. I opt to drop it. :)
